language: node_js

node_js:
  - "lts/*"
  - "10"
  - "8"

notifications:
  email:
    receipients:
      - pingpong@bytecode.nl

install:
  - yarn

script:
  - yarn run lint

cache:
  yarn: true
  directories:
    - node_modules
